// This file is normally generated by the FlutterFire CLI (`flutterfire configure`).
// Run `flutterfire configure` at the project root to create a real
// configuration for your Firebase project. Replace the values below
// with those appropriate for your apps if you choose to handcraft it.

// ignore_for_file: constant_identifier_names, unused_import

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // TODO: replace with web options
      return FirebaseOptions(
        apiKey: 'YOUR_API_KEY',
        authDomain: 'YOUR_AUTH_DOMAIN',
        projectId: 'YOUR_PROJECT_ID',
        storageBucket: 'YOUR_STORAGE_BUCKET',
        messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
        appId: 'YOUR_APP_ID',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return FirebaseOptions(
          apiKey: 'AIzaSyA6g5f730OtfAWsKFSLFpTvAB4vzBEwCfU',
          appId: '1:701125601827:android:00498974eb0c4a27731f96',
          messagingSenderId: '701125601827',
          projectId: 'run-sync-a470f',
        );
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        // TODO: replace with iOS/macOS options
        return FirebaseOptions(
          apiKey: 'YOUR_API_KEY',
          appId: 'YOUR_APP_ID',
          messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
          projectId: 'YOUR_PROJECT_ID',
          iosBundleId: 'YOUR_BUNDLE_ID',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }
}
